services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: "${APP_NAME}"
        restart: always
        working_dir: /app
        volumes:
            - .:/app
        depends_on:
            - mariadb
        networks:
            - label-maker-network
        healthcheck:
            test: [ "CMD", "php", "/app/artisan", "migrate:status" ]
            interval: 30s
            timeout: 5s
            retries: 5

    nginx:
        image: nginx:latest
        container_name: laravel-nginx
        restart: always
        ports:
            - "${APP_PORT-80}:80"
            - "${APP_SSL_PORT-443}:443"
        volumes:
#            - ./public:/app/public
            - ./nginx/default.conf.template:/etc/nginx/default.conf.template
        environment:
            - APP_NAME=${APP_NAME:-label-maker}
        command: /bin/sh -c "envsubst '$$APP_NAME' < /etc/nginx/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
        depends_on:
            - app
        networks:
            - label-maker-network

    mariadb:
        image: mariadb:noble
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        container_name: mariadb
        restart: always
        environment:
            - MARIADB_USER=${DB_USERNAME:-laravel}
            - MARIADB_PASSWORD=${DB_PASSWORD:-secret}
            - MARIADB_DATABASE=${DB_DATABASE:-label-maker}
            - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD:-my-secret-pw}
        volumes:
            - mariadb_data:/var/lib/mysql
        networks:
            - label-maker-network
        healthcheck:
            test: [ "CMD", "mariadb", "-u", "root", "-p$DB_ROOT_PASSWORD", "-e", "SELECT 1;" ]
            interval: 30s
            timeout: 5s
            retries: 3

volumes:
    mariadb_data:

networks:
    label-maker-network:
        driver: bridge
